##  数据库配置 ##
server:
  port: 8080
spring:
  datasource:
    druid:
      one:
        url: jdbc:mysql://172.16.11.74:3306/integrated-automation?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456

      two:
        url: jdbc:mysql://81.69.15.221:3306/test?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root

